image: 'ruby:2.3.3'

stages:
  - testing

before_script:
  - gem install bundler --no-ri --no-rdoc
  - bundle install --path vendor/bundle

cache:
  paths:
    - vendor/bundle

scss-lint:
  type: test
  stage: testing
  environment: testing
  script:
    - bundle exec rake 'scss_lint[--format, Stats]'
