REVIEW_CHAR_BG: |-
  #main-info.vocabulary, #character.vocabulary {
      background-color: /*[[VOCAB_COLOR]]*/ !important
  }

  #main-info.kanji, #character.kanji {
      background-color: /*[[KANJI_COLOR]]*/ !important
  }

  #main-info.radical, #character.radical {
      background-color: /*[[RADICALS_COLOR]]*/ !important
  }

  #main-info.vocabulary #character, #main-info.kanji #character,
  #main-info.radical #character, #main-info #meaning,
  #character, #stats, #summary-button, #header-buttons {
      color: #232629 !important
  }

RADICALS_COLOR:    '#3daee9'
KANJI_COLOR:       '#fdbc4b'
VOCAB_COLOR:       '#2ecc71'
BURNED_COLOR:      '#da4453'
REVIEW_READING_BG: 'transparent'
REVIEW_MEANING_BG: 'transparent'
